### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by akaspin** [ostinelli/misultin#21]
Two requests:

```
POST /chunk/a5b4608831c2e1e00c326ae3dc2873fee66cdf8f/524288
POST /chunk/a5b4608831c2e1e00c326ae3dc2873fee66cdf8f/1048576
```

But they just not handled. `loop fun` not invoked.

**Comment by ostinelli** [comment]
hy akaspin, could you please be less cryptic? :)

please provide complete code and additional files to reproduce what you signal. thank you.

**Comment by akaspin** [comment]
Ohh sorry. I'll try to detail. For example - simple server:

```
misultin:start_link([
                     {port, 8500}, 
                     {loop, fun(Req) -> Req:ok("ok") end}]).
```

...and some requests with ibrowse:
- `POST deal/start/750c91217d4c622dea11400035a68eb145930e7c/fw1.txt` with some binary data - OK
- `GET chunk/c40fc47f7b9c6a7d6a34d54540774a7282e38279/524288/524288` - OK
- `POST chunk/c13b39cbbb01a675969ff65042db118d6c0433c2/1048576` with 512K of binary data - No reaction.

I'm stuck. With mochiweb all working fine.

**Comment by ostinelli** [comment]
hi akaspim, misultin POST size was set by default very small. i've now upgraded it to 4 MB. please check if this works now for you.

you can set this using the option {post_max_size, integer()}, for instance {post_max_size, 4_1012_1012} will allow post size of 4MB.

Source: https://github.com/ostinelli/misultin/wiki/Exports

btw, if this is your case you could have simply seen it since you should have received a "413 post request entity too large" http error on your request.

**Comment by akaspin** [comment]
Thanks for the clarification. I'm migrated project from mochiweb to misultin. Now all works faster.

**Comment by ostinelli** [comment]
you're welcome.

which project? are there any public benchmarks?

**Comment by akaspin** [comment]
Sorry. I shall not disclose any details about the project at this stage of development. I can say two things: terabytes of data and tons of simultaneous connections.

**Comment by akaspin** [comment]
And again big `POST` requests not not processed. 

For example in third post I wrote test that sends a series of `POST` requests with gradually increasing bodies (from 1024 bytes to 1M).

On `misultin-0.7.1` - test passed.

But on `master` (0.8-dev) test breaks on body sizes about 39000-53248 bytes and above.

Options `recv_timeout` and `post_max_size` do not help.

**Comment by ostinelli** [comment]
hi,

please post test case code to reproduce issue and encountered.

**Comment by akaspin** [comment]
I'm create test here: https://gist.github.com/1061832

On `0.8-dev` it timed out

```
incr_test: incr_upload_test_ (Upload 49152 bytes)...*timed out*
```

`fun(Req) -> Req:ok("ok") end` just not run.

On `misultin-0.7.1` all ok

**Comment by ostinelli** [comment]
this what i get:

  All 2049 tests passed.
 ok.

latest misultin in the dev-0.8 trunk, R14B02, ibrowse 2.2.

**Comment by akaspin** [comment]
Just two cents. On misultin at https://github.com/ostinelli/misultin/commit/8a38c10ea963622856734dd228ef679777d3427b.
Test `*timed out*` in one case out of five. But on https://github.com/ostinelli/misultin/commit/28f9e977ad65254eae5c0b38a26f62251fe08c0c test timed out almost always. On `0.7.1` this never happens.

The problem occurs sporadically. In my test VM (Ubuntu natty x64, 4 cores, 512M, Erlang R14B02 - like all nodes in cluster) timeouts begin with about 200 requests. Irregularly. Most likely, there a memory leak or trashing. No matter what size to begin. The more queries - the sooner the start time-outs. 

And I was very worried - why this does not never happen in `0.7.1`. I use misultin in production system and prefer `HEAD`. But now I'm at a loss. Perhaps the point in a test VM.

**Comment by ostinelli** [comment]
hi,

why do you say that "Most likely, there a memory leak or trashing"? is the erlang VM crashing or hanging in any way? have you checked memory usage in the erlang VM itself, or have you seen memory usage continuously increase at OS level eaten by the erlang process? do you have any evidence that supports what you say?

moreover, are you running ibrowse on the same target node or from another node? because if you are running it from the same node (like it would seem from your gist) and receiving its _timeout_ replies, it means that its node is not down. so again, why do you think there are memory leaks?

on another note, did you try to enable verbose logging and see what happens? you can do so simply by compiling misultin with "make debug". please post end of console log here.

also, can you please try to find from which commit this happens? this could be helpful in finding out which are the differences. for instance, how does the https://github.com/ostinelli/misultin/commit/24c97ce4efa96b4075cb9445a99d5474207f2d41 behave?

finally:

. did you compile erlang yourself, or is it an ubuntu package?
. are you using ibrowse 2.2?

let's try and nail down the problem that you are experiencing.

**Comment by akaspin** [comment]
Ok. Some real features. Now accept function writes data to disk. Start size 512K, end size 1M. 512 requests. For more pleasure, I run some applications (ie `gproc`) on test setup.

Test on each revision run three times on ten VM in cluster. Ie, each test was run thirty times.
- 8d4ee23 (0.7.1) - ok
- a33a340 - ok
- bdaff35 - ok
- 5c5a811 - ok
- 54008f5 - errors on compillation
- 1b34411 - ok
- ca8738a - ok
- 7bbf637 - ok
- 0855dfb - ok
- bf6dc4d - ok
- 3e81554 - ok
- 9a928e2 - ok
- be8c7cb - ok
- 9e74bd4 - ok
- 51ccce2 - ok
- ...
- 24c97ce - ok
- c9422cb - **Yep! It's our hero! Timeouts on first run.** 
- ... - timed out
- 8a38c10 HEAD - timed out

UPD: `{recbuf, 8192}` in misultin options completely solved the problem. Most likely, you need to describe this behavior in the documentation.

**Comment by ostinelli** [comment]
this is why i pinpointed the one which i believed could lead to trouble: the default recbuf option might collide with the one set by ubuntu by default. i wouldn't recommend solving it with recbuf at this stage, since this can hide MTU and other issues on your machine.

can you please confirm that if you start your tests on a freshly started machine, c9422cb times out and that, again on a freshly started machine 24c97ce does not?

**Comment by ostinelli** [comment]
pushed a modification so that recbuf is not set to default by the OS.

can you please take away the {recbuf, 8192} option in misultin settings and try again with d37a2f86ea329841175b?

**Comment by akaspin** [comment]
All tests were run on three times on fresh machines without `recbuf` option. All tests from c9422cb to 8a38c10 failed on all three runs. 

I force test sequence on c9422cb. Ten times - always fails.

d37a2f8 - all tests ok. With and without `recbuf`. Thanks a lot.
