### ISSUE TITLE
Sessions for Websockets

### ISSUE THREAD

**Issue by egobrain** [ostinelli/misultin#80]
That's really good idea to create session server, 
but can you create it for misultin_ws module, please ?

**Comment by ostinelli** [comment]
hi egobrain, why would you need that? websockets are (kinda) persistent by definition.

could you expand on your needs?

**Comment by egobrain** [comment]
In my service i want accept connection only from authorized users.
Information about user authorization can be stored in session.
Am i right? Or there is a better way ?

 Roberto Ostinelli  
reply@reply.github.com  
:

**Comment by ostinelli** [comment]
there are many different ways, all of which are outside the scope of this discussion :)

i get you are requesting to make sessions accessible to websockets, so i'll dig into that.

thank you,

r.

**Comment by egobrain** [comment]
Thank you very much.
And i've got some more ideas :) i'll write about them later.

 Roberto Ostinelli  
reply@reply.github.com  
:

**Comment by ostinelli** [comment]
hi egobrain,

i've been thinking about this.

sessions are a 'trick' to circumvent the fact that http is a stateless protocol. thus, most implementations (misultin's one too) generally use a cookie to save session ids, used then to retrieve data saved on the server.

websockets, on the contrary, are persistent connections, which can easily keep the state in the process which is handling them. moreover, cookies are generally out of the game.

therefore, even if conceptually these interactions are very different, a practical need i can try to understand from your request may be:

. save user authentication info (such as her name) during normal http authentication requests;
. when a websocket is used, allow it to retrieve this info too.

since websockets cannot normally create cookies, the requested functionality can _only read_ existing sessions, and not create new ones.

implemented: dce39c9b6c389066906f865467f2291d6033827e

please let me know if this works for you.

r.

**Comment by egobrain** [comment]
Yes, that's it. Thank you!
